src/J2N/Threading/ThreadJob.cs
This supersedes #14, which accidentally targeted the wrong branch.
This is an issue for the `ConcurrentMergeScheduler` in Lucene.NET because it requires the background thread to signal the calling thread using this exception. This is confirmed to be a contributor to the `TestThreadInterruptDeadlock()` and  `TestTwoThreadsInterruptDeadlock()` test failures.
=> J2N.Threading.ThreadJob: Allow ThreadInterruptedException to propagate to the calling thread

src/J2N/IO/Buffer.cs, src/J2N/IO/ByteBuffer.cs, src/J2N/IO/CharBuffer.cs, src/J2N/IO/CharSequenceAdapter.cs, src/J2N/IO/DoubleBuffer.cs, src/J2N/IO/Int16Buffer.cs, src/J2N/IO/Int32Buffer.cs, src/J2N/IO/Int64Buffer.cs, src/J2N/IO/MemoryMappedFiles/ReadWriteMemoryMappedViewByteBuffer.cs, src/J2N/IO/ReadOnlyCharArrayBuffer.cs, src/J2N/IO/ReadWriteCharArrayBuffer.cs, src/J2N/IO/ReadWriteDoubleArrayBuffer.cs, src/J2N/IO/ReadWriteHeapByteBuffer.cs, src/J2N/IO/ReadWriteInt16ArrayBuffer.cs, src/J2N/IO/ReadWriteInt32ArrayBuffer.cs, src/J2N/IO/ReadWriteInt64ArrayBuffer.cs, src/J2N/IO/ReadWriteSingleArrayBuffer.cs, src/J2N/IO/SingleBuffer.cs, src/J2N/Resources/Strings.Designer.cs, src/J2N/Resources/Strings.resx
`J2N.IO.Buffer` + subclasses: Improved guard clauses by throwing more specific exceptions (`ArgumentOutOfRangeException` rather than `ArgumentException`), adding better error descriptions, and avoiding the guard clause checks being accidentally overridden because of operator overrides.
=> Buffers: Improved guard clauses

src/J2N/Character.cs, tests/J2N.Tests/TestCharacter.cs
This is to cover the Java 1.5 API that added a constructor overload of String that accepts code points that .NET is lacking.
Also included Apache Harmony's `String` class test and Lucene.NET's `UnicodeUtil` test.
=> J2N.Character: Added ToString() methods to convert code point arrays to strings.

src/J2N/MathExtensions.cs
These JDK methods are in use by https://github.com/randomizedtesting/randomizedtesting, so putting them in J2N where they can be shared.
=> J2N.MathExtensions: Added NextUp(), NextDown(), and NextAfter() methods for both float and double types.

Directory.Build.targets
Support was added again in .NET Core 2.0.4: https://docs.microsoft.com/en-us/dotnet/standard/serialization/binary-serialization#net-core
See also: https://github.com/dotnet/runtime/issues/23341
=> Enabled serializable exceptions on .NET Core/.NET 5

Directory.Build.targets, src/J2N/Threading/ThreadJob.cs
This supersedes #22, which targeted the wrong branch.
`J2N.Threading.ThreadJob`: Added support for original stack trace using `ExceptionDispatchInfo` on .NET Framework 4.5+ and marked the `ThreadJob.Debug` property obsolete, since this feature is always on.
=> Fixed rethrow logic of ThreadJob to preserve the stack trace of the exception

src/J2N/Text/ParseException.cs, tests/J2N.Tests/Text/TestParseException.cs
This supersedes #25, which targeted the wrong branch.
This is a checked exception in Java and `NumberFormatException` is unchecked. This isn't really a problem per se in .NET, but there is only 1 exception named `FormatException` that sort of maps to both cases. However, if you have an application where the exception handling is so complex that you need to have a `ParseException` that is different from `FormatException`, then here it is. This also can solve compatibility with throwing a platform exception named `ParseException` that needs to be passed between ported libraries as the same type.
=> Added ParseException + tests

src/J2N/Collections/BitSet.cs
Corrected documentation about `IndexOutOfRangeException`, which should be `ArgumentOutOfRangeException`
=> Fixed BitSet documentation

src/J2N/Text/StringFormatter.cs, tests/J2N.Tests/Text/TestStringFormatter.cs
`StringFormatter` had been changed to use nullable reference types in #23, however it appears that the feedback provided by the nullable support of `ICustomFormatter` was incorrect and doesn't match the documentation. `null` values are valid and allowed to be returned from `ICustomFormatter.Format()` to specify that the custom formatter couldn't handle the formatting and also `IFormattable.ToString(string, IFormatProvider)` allows (and requires) a `null` format to be passed in certain scenarios, such as when the type is an `enum`.
This reverts the implementation to returning `null` in cases we don't handle.
=> Fixed enum support in StringFormatter

build/dependencies.props, src/J2N/Character.cs, tests/J2N.Tests/J2N.Tests.csproj, tests/J2N.Tests/TestCharacter.cs
- Added UTF-32 code point overloads of `Digit()` and `GetNumericValue()` to the `Character` class.
- Upgraded the existing methods from Unicode 3.0.0 to Unicode 10.0.
- Optimized ASCII digit lookups with a small (128 byte) static memory tradeoff.
=> J2N.Character: Added code point overloads of Digit() and GetNumericValue()

src/J2N.TestFramework/TestCase.cs, src/J2N/Collections/Arrays.cs, src/J2N/Collections/Generic/EqualityComparer.cs, src/J2N/MathExtensions.cs, src/J2N/Time.cs, tests/J2N.Tests/Collections/TestArrays.cs, tests/J2N.Tests/IO/TestByteBuffer2.cs, tests/J2N.Tests/IO/TestDoubleBuffer2.cs, tests/J2N.Tests/IO/TestSingleBuffer2.cs, tests/J2N.Tests/TestTime.cs
- BUG: Updated `float.MinValue` and `double.MinValue` to `float.Epsilon` and `double.Epsilon`, respectively (Epsilon is the corresponding constant in .NET)
- Added `DebuggerStepThrough` attribute in test framework assert methods
- Fixed floating point comparison logic in J2N.Collections.Generic.EqualityComparer
- Added `MathExtensions.CopySign()` method
- Added `J2N.Collections.Arrays.CopyOf()` method (internal)
-  BUG: J2N.Time: Fixed implementations of both `NanoTime()` and `CurrentTimeMilliseconds()` to match the JDK and added tests. Also added field for `UnixEpoch` and methods for `GetTimeSpanSinceUnixEpoch()` and `GetMillisecondsSinceUnixEpoch()`. See apache/lucenenet#492
=> 2021 July Miscellaneous Bug Fixes and Updates

tests/J2N.Tests.xUnit/Collections/Concurrent/LurchTable/LurchTable.Generic.Tests.cs
LurchTable uses a different lock for `Remove()` than for each enumerator instance, so while deleting is allowed, it is not synchronized. This is apparently by design, but it is not something we need to worry about for Lucene.Net or ICU4N.
=> Commented failing LurchTable enumerator test

src/J2N/Character.cs, tests/J2N.Tests/TestCharacter.cs
The JDK adds some Unicode whitespace characters, but doesn't follow the spec of any Unicode version. The .NET `System.Character.IsWhiteSpace()` method *does* follow the Unicode spec. This patches the method to behave like Java, although in most cases in practice it probably makes more sense to call `char.IsWhiteSpace()` and it is unlikely to make a difference in most cases.
Specifically, there are 4 Unicode characters that this method returns `false` on this method that return `true` in .NET, but otherwise it is an exact match:
1. 0x0085
2. 0x00A0
3. 0x2007
4. 0x202F
=> BREAKING: Fixed Character.IsWhiteSpace() to match JDK

Directory.Build.targets, src/J2N/Text/StringFormatter.cs, tests/J2N.Tests/Text/TestStringFormatter.cs
This supersedes #44, which targeted the wrong branch.
This adds a constructor overload accepting `IFormatProvider` to `StringFormatter`. Note that while `StringFormatter` is marked as `[Serializable]`, in .NET Core and newer platforms, none of the `IFormatProvider` implementations are serializable.
Since in Java, `Locale` is often used as a field and may be a field of a serializable class, we recommend refactoring the class to accept an `IFormatProvider` as a method argument rather than using a field, where possible. If that is not possible and serialization is required, it is recommended to create a custom `IFormatProvider` that wraps the .NET type in order to serialize and deserialize its state. Note that the `formatProvider` field in `StringFormatter` will automatically be serialized …
=> J2N.Text.StringFormatter: Added constructor overload for IFormatProvider

src/J2N/Threading/ThreadJob.cs
If set out of bounds in .NET, the Priority will be corrected to either ThreadPriority.Lowest or ThreadPriority.Highest to avoid exceptions when using Java priority numbers.
=> J2N.Threading.ThreadJob: Don't swallow exceptions when getting/setting Priority

src/J2N/Character.cs, src/J2N/Resources/Strings.Designer.cs, src/J2N/Resources/Strings.resx, tests/J2N.Tests/TestCharacter.cs
Added ReadOnlySpan<char> overloads for CodePointAt, CodePointBefore, CodePointCount, and OffsetByCodePoints + tests
```c#
namespace J2N
{
public static class Character
{
public static int CodePointAt(this ReadOnlySpan<char> seq, int index)
public static int CodePointBefore(this ReadOnlySpan<char> seq, int index)
public static int CodePointCount(this ReadOnlySpan<char> seq)
public static int OffsetByCodePoints(this ReadOnlySpan<char> seq, int index, int codePointOffset)
}
}
```
=> J2N.Character: Added ReadOnlySpan<char> overloads for working with codepoints

Directory.Build.targets, src/J2N/Text/ValueStringBuilderChunkIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderChunkIndexer.cs
Added `ValueStringBuilderChunkIndexer` + tests, which will be used to optimize methods that iterate through `StringBuilder` via index.
Benchmarks of `IndexOf()` can be seen at https://github.com/NightOwl888/BenchmarkPlayground/commit/b9642194a302c3dc5dd239d316614a8e48b0e0d4. The difference in performance is significant.
=> J2N.Text: Added ValueStringBuilderChunkIndexer + tests

Directory.Build.targets, src/J2N/Text/ValueStringBuilderArrayPoolIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderArrayPoolIndexer.cs
Added `ValueStringBuilderArrayPoolIndexer` + tests, which will be used to optimize methods that iterate through `StringBuilder` via index (in cases where `GetChunks()` is not supported).
=> J2N.Text: Added ValueStringBuilderArrayPoolIndexer + tests

Directory.Build.targets, src/J2N/Text/StringBuffer.cs, src/J2N/Text/StringBuilderExtensions.cs, src/J2N/Text/ValueStringBuilderArrayPoolIndexer.cs, tests/J2N.Tests/Text/TestStringBuilderExtensions.cs, tests/J2N.Tests/Text/TestValueStringBuilderArrayPoolIndexer.cs
New APIs:
```c#
{
public static class StringBuilderExtensions
{
public static StringBuilder Append(this StringBuilder text, ReadOnlySpan<char> charSequence);
public static StringBuilder Insert(this StringBuilder text, int index, ReadOnlySpan<char> charSequence);
public static StringBuilder InsertCodePoint(this StringBuilder text, int index, int codePoint);
}
}
```
Optimized APIs:
- Append()
- AppendCodePoint()
- CompareToOrdinal()
- IndexOf()
- Insert()
- LastIndexOf()
- Replace()
- Reverse()
This also fixes several bugs in `ValueStringBuilderArrayPoolIndexer` and fixes #58.
These optimizations take advantage of `ArrayPool`, `ValueStringBuilderArrayPoolIndexer`, and `ValueStringBuilderChunkIndexer` to provide faster indexing through the `StringBuilder` class.
=> PERFORMANCE: J2N.Text.StringBuilderExtensions: Optimizations

src/J2N/Character.cs, src/J2N/Text/CharArrayExtensions.cs, src/J2N/Text/StringBuilderExtensions.cs, src/J2N/Text/ValueStringBuilderChunkIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderArrayPoolIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderChunkIndexer.cs
The `upperBounds` array is allocated only if we exceed 32 chunks or 65535 characters,. Being that this is a ref struct that is used once per method call, it makes sense to reuse the array if we spill over these values to make optimal use of memory.
This makes `ValueStringBuilderChunkIndexer` disposable, but it is a fair tradeoff for what we gain.
=> PERFORMANCE: J2N.Text.ValueStringBuilderChunkIndexer: Use ArrayPool for upperBounds array

src/J2N/Text/AppendableExtensions.cs, src/J2N/Text/ISpanAppendable.cs, src/J2N/Text/StringBuffer.cs, src/J2N/Text/StringBuilderCharSequence.cs, tests/J2N.Tests/Text/TestAppendableExtensions.cs, tests/J2N.Tests/Text/TestStringBuffer.cs
Added `ISpanAppendable` interface and `AppendableExtensions` class to provide an extension method `IAppendable.Append(ReadOnlySpan<char>)` without a breaking change to `IAppendable`.
=> J2N.Text: Added ISpanAppendable interface and AppendableExtensions class

Directory.Build.targets, src/J2N/Text/StringBuffer.cs, src/J2N/Text/StringBuilderCharSequence.cs, src/J2N/Text/StringBuilderExtensions.cs
```c#
{
public class StringBuffer
{
public void CopyTo(int sourceIndex, Span<char> destination, int count); // .NET Framework 4.5+
public StringBuffer Insert(int index, ReadOnlySpan<char> value); // New legacy support for .NET Framework 4.5+
public StringBuffer InsertCodePoint(int index, int codePoint);
}
}
```
- `Directory.Build.Targets`: Removed `FEATURE_CHARARRAYPOINTERS`, which is a duplicate of `FEATURE_STRINGBUILDER_APPEND_CHARPTR`
- `J2N.Text.StringBuffer::Append(StringBuffer, int, int)`: Fixed implementation to correctly pass in `StringBuffer.builder` to the `Append` call
- Directory.Build.targets: Added `FEATURE_STRINGBUILDER_APPEND_STRINGBUILDER` to optimize for when this overload is available in .NET.
=> J2N.Text.StringBuffer: Fixed bugs and added new APIs

src/J2N/Character.cs, src/J2N/Text/CharArrayCharSequence.cs, src/J2N/Text/CharArrayExtensions.cs, src/J2N/Text/CharSequenceComparer.cs, src/J2N/Text/StringBuilderCharSequence.cs, src/J2N/Text/StringBuilderExtensions.cs, src/J2N/Text/StringCharSequence.cs, src/J2N/Text/StringExtensions.cs, src/J2N/Text/ValueStringBuilderChunkIndexer.cs, src/J2N/Text/ValueStringBuilderChunkedArrayIndexer.cs, src/J2N/Text/ValueStringBuilderIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderChunkIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderChunkedArrayIndexer.cs, tests/J2N.Tests/Text/TestValueStringBuilderIndexer.cs
New API:
```c#
{
public ref struct ValueStringBuilderIndexer
{
public ValueStringBuilderIndexer(StringBuilder stringBuilder, bool iterateForward = true);
public void Dispose();
public bool IterateForward { get; }
public char this[index] { get; set }
}
}
```
Indexing through `System.Text.StringBuilder` is painfully slow. The purpose of this type is to wrap `StringBuilder` to allow faster access to the chars via index.
When supported, it uses `StringBuilder.GetChunks()` to access the chars. It keeps track of the bounds of each chunk and will switch to another chunk if an out of bounds index is requested.
If `StringBuilder.GetChunks()` is not supported, it uses an array. If the length of the `StringBuilder` is more than 512 characters, the array is limited to 512 …
=> J2N.Text: Added ValueStringBuilderIndexer for end users - optimizes iteration of StringBuilder via index

src/J2N/Memory/MemoryExtensions.cs, src/J2N/Text/StringBuilderExtensions.cs, src/J2N/Text/StringExtensions.cs, tests/J2N.Tests/Memory/TestMemoryExtensions.cs, tests/J2N.Tests/Text/TestStringExtensions.cs
Added optimized `ReverseText()` methods to reverse strings while respecting the correct order of surrogate pairs, just like the `StringBuilderExtensions.Reverse()` method.
These are the same operation as Java's `StringBuilder.reverse()` method, except they don't require an instance of `StringBuilder` to function.
=> J2N.Text.StringExtensions, J2N.Memory.MemoryExtensions: Added optimized ReverseText() methods

src/J2N/Character.cs, src/J2N/Text/ValueStringBuilderChunkIndexer.cs, src/J2N/Text/ValueStringBuilderChunkedArrayIndexer.cs, src/J2N/Text/ValueStringBuilderIndexer.cs, tests/J2N.Tests/TestCharacter.cs
Added overloads of `CodePointAt()` and `CodePointBefore()` for use with `ValueStringBuilderIndexer`, since these methods are designed to be called inside of a loop.
=> J2N.Character: Added overloads of CodePointAt() and CodePointBefore()

.build/TestTargetFramework.props, .build/azure-templates/publish-test-results-for-target-frameworks.yml, azure-pipelines.yml, src/J2N.TestFramework/J2N.TestFramework.csproj, src/J2N/J2N.csproj
There are a few performance reasons why this is now a benefit:
-  The `StringBuilder.Append(char*, int)` method (added in `net46`) is a significant performance benefit to legacy ReadOnlySpan<char> support. 
- The `Buffer.MemoryCopy()` method is available, which makes the `float/double` parsing significantly faster.
- The `Array.Empty<T>()` method is available, so we don't have to roll our own solution.
Added test target for `net472`, which will be used to test `net45` (`net48` now tests `net462` instead of `net45`). See: https://github.com/NightOwl888/J2N/blob/89276f7419c9940c4f7795aebdee35c5dcff3750/.build/TestTargetFramework.props#L19-L27
This also changes tests to run on background jobs in parallel to speed up the test runs.
=> PERFORMANCE: Added target for net462

src/J2N/Text/CharArrayExtensions.cs, src/J2N/Text/StringBuilderExtensions.cs, src/J2N/Text/StringExtensions.cs, tests/J2N.Tests/Text/TestCharArrayExtensions.cs, tests/J2N.Tests/Text/TestStringBuilderExtensions.cs, tests/J2N.Tests/Text/TestStringExtensions.cs
New APIs:
```c#
{
public static class CharArrayExtensions
{
public static int CompareToOrdinal(this char[]? str, ReadOnlySpan<char> value);
}
public static class StringBuilderExtensions
{
public static int CompareToOrdinal(this StringBuilder? text, ReadOnlySpan<char> value);
}
public static class StringExtensions
{
public static int CompareToOrdinal(this string? str, ReadOnlySpan<char> value);
}
}
```
Null comparison checks are performed against `ReadOnlySpan<char>.Empty`.
=> J2N.Text (CharArrayExtensions + StringBuilderExtensions + StringExtensions): Added ReadOnlySpan<char> overload of CompareToOrdinal()

src/J2N/Text/StringBuilderExtensions.cs, tests/J2N.Tests/Text/TestStringBuilderExtensions.cs
New APIs:
```c#
{
public static class StringBuilderExtensions
{
public static StringBuilder Replace(this StringBuilder text, int startIndex, int count, ReadOnlySpan<char> newValue);
}
}
```
=> J2N.Text.StringBuilderExtensions: Added Replace() overload that accepts ReadOnlySpan<char>

src/J2N/Memory/MemoryExtensions.cs, src/J2N/MemoryExtensions.cs, src/J2N/Text/StringExtensions.cs, tests/J2N.Tests/Memory/TestMemoryExtensions.cs, tests/J2N.Tests/TestMemoryExtensions.cs
This moves `MemoryExtensions` from the J2N.Memory namespace (unreleased) to the J2N namespace.
New APIs:
```c#
namespace J2N
{
public static class MemoryExtensions
{
public static int IndexOf(this ReadOnlySpan<char> text, char value);
public static int IndexOf(this Span<char> text, char value);
public static int IndexOf(this ReadOnlySpan<char> text, int codePoint);
public static int IndexOf(this Span<char> text, int codePoint);
public static int LastIndexOf(this ReadOnlySpan<char> text, char value);
public static int LastIndexOf(this Span<char> text, char value);
public static int LastIndexOf(this ReadOnlySpan<char> text, int codePoint);
public static int LastIndexOf(this Span<char> text, int codePoint);
}
}
```
The `char` overloads are only provided to cascade the call to …
=> J2N.MemoryExtensions: Added IndexOf(codePoint) and LastIndexOf(codePoint) extension methods

src/J2N/Text/StringExtensions.cs, tests/J2N.Tests/Text/TestStringExtensions.cs
New APIs:
```c#
{
public static class StringExtensions
{
public static bool ContentEquals(this string? text, ReadOnlySpan<char> charSequence);
public static bool ContentEquals(this string? text, ReadOnlySpan<char> charSequence, StringComparison comparisonType);
}
}
```
=> J2N.Text.StringExtensions: Added ReadOnlySpan<char> overload of ContentEquals()

src/J2N/Text/StringExtensions.cs, tests/J2N.Tests/Text/TestStringExtensions.cs
New APIs:
```c#
{
public static class StringExtensions
{
public static bool RegionMatches(this string text, int thisStartIndex, ReadOnlySpan<char> other, int otherStartIndex, int length, StringComparison comparisonType);
}
}
```
This method has extra logic to ensure it will return a result if the bounds are out of range, but if it is not needed, slicing the span and using `System.MemoryExtensions.Equals(ReadOnlySpan<char>)` is a better option. Therefore, this method is intended primarily as a transition mechanism during porting.
=> J2N.Text.StringExtensions: Added ReadOnlySpan<char> overload to RegionMatches()

.build/TestReferences.Common.targets, .build/TestTargetFramework.props, .build/azure-templates/install-android-sdk.yml, .build/azure-templates/publish-test-results-for-target-frameworks.yml, .build/dependencies.props, Directory.Build.targets, J2N.sln, NuGet.config, azure-pipelines.yml, src/J2N/Collections/Concurrent/LurchTable.cs, src/J2N/Collections/Generic/ArraySortHelper.cs, src/J2N/Collections/Generic/LinkedDictionary.cs, src/J2N/J2N.csproj, src/J2N/MemoryExtensions.cs, src/J2N/Numerics/DotNetNumber.Parsing.cs, src/J2N/Text/ValueStringBuilder.cs, tests/J2N.Tests/IO/TestByteBuffer2.cs, tests/J2N.Tests/IO/TestCharBuffer2.cs, tests/J2N.Tests/IO/TestDoubleBuffer2.cs, tests/J2N.Tests/IO/TestInt16Buffer2.cs, tests/J2N.Tests/IO/TestInt32Buffer2.cs, tests/J2N.Tests/IO/TestInt64Buffer2.cs, tests/J2N.Tests/IO/TestSingleBuffer2.cs, tests/J2N.Tests/J2N.Tests.csproj, tests/J2N.Tests/TestAssemblyExtensions.cs, tests/J2N.Tests/TestCharacter.cs, tests/J2N.Tests/Text/TestValueStringBuilder.cs, tests/J2N.Tests/Threading/TestThreadJob.cs
This fixes the net40 target so it supports key features in
- System.Memory
- System.Buffers
- System.Runtime.CompilerServices.Unsafe
which can significantly reduce allocations when used. All of the features in these libraries can now be utilized without conditionally compiling. It also means that the ref struct `ValueStringBuilder` can now be utilized on net40 as well, further reducing conditional compilation.
This PR does not (yet) remove the conditional compilation. This will take a bit more work because there is quite a bit of duplicate code for the `string` vs `ReadOnlySpan<char>` overloads. We will now be able to cascade all of the `string` overload calls to the `ReadOnlySpan<char>` internal methods.
This PR includes an update to get Xamarin.Android tests running again, since the …
=> Added support for Span<T>/ReadOnlySpan<T> in net40

src/J2N/Text/StringBuilderExtensions.cs
`J2N.Text.StringBuilderExtensions::Replace()`: Reuse expansion memory by declaring it on the stack or using an array pool
=> PERFORMANCE: J2N.Text.StringBuilderExtensions::Replace(): Reuse expansion memory

azure-pipelines.yml
Nerdbank.GitVersioning requires a deep clone to function and Azure DevOps has changed the default of new pipelines to create a shallow clone. This fixes that issue.
More about the issue can be found at: https://github.com/dotnet/Nerdbank.GitVersioning/blob/main/doc/cloudbuild.md#azure-pipelines
=> azure-pipelines.yml: Use deep clone for Nerdbank.GitVersioning

src/J2N/Character.cs, tests/J2N.Tests/TestCharacter.cs
J2N.Character: Added overload of `ToChars()` that accepts a `Span<char>` buffer and returns a `ReadOnlySpan<char>` sliced to the appropriate length. This is to replace the overload that returns a new `char[]`, which will allow memory reuse (and the use of the stack).
New APIs:
```c#
namespace J2N
{
public static class Character
{
public static ReadOnlySpan<char> ToChars(int codePoint, Span<char> buffer);
}
}
```
=> J2N.Character: Added overload of ToChars() that accepts a Span<char> and returns ReadOnlySpan<char>

Directory.Build.props, Directory.Build.targets, src/J2N/Collections/Generic/List.cs, src/J2N/J2N.csproj, src/J2N/Runtime/InteropServices/CollectionMarshal.cs, tests/J2N.Tests.xUnit/AssertExtensions.cs, tests/J2N.Tests.xUnit/J2N.Tests.xUnit.csproj, tests/J2N.Tests.xUnit/Runtime/InteropServices/CollectionMarshalTests.cs, tests/J2N.Tests/Collections/Generic/TestList.cs
J2N.Runtime.InteropServices: Added `CollectionMarshal` class to provide access to the underlying memory of a `List<T>`. This also adds a public `List<T>.EnsureCapacity(int)` method.
New APIs:
```c#
namespace J2N.Runtime.InteropServices
{
public static class CollectionMarshal
{
public static Span<T> AsSpan<T>(List<T>? list)
public static void SetCount<T>(List<T> list, int count);   
}
}
namespace J2N.Collections.Generic
{
public class List<T>
{
public int EnsureCapacity(int capacity);
}
}
```
=> J2N.Runtime.InteropServices: Added CollectionMarshal class

src/J2N/Collections/Generic/Dictionary.cs, src/J2N/Collections/Generic/SortedDictionary.cs, src/J2N/Collections/Generic/SortedSet.cs, tests/J2N.Tests.xUnit/Collections/Generic/Dictionary/Dictionary.Generic.Tests.Keys.cs, tests/J2N.Tests.xUnit/Collections/Generic/Dictionary/Dictionary.Generic.Tests.Values.cs
Removed breaking binary API changes for `Dictionary<TKey, TValue>`, `SortedDictionary<TKey, TValue>`, and `SortedSet<T>`. This commit will need to be reverted in a major version bump to match the BCL APIs.
=> Reverted breaking API changes for 2.1.0 so we don't have to bump to 3.0.0

.build/TestTargetFramework.props, .build/runbuild.ps1, docs/building-and-testing.md
Fixes test run issues:
- Only run .NET Framework tests on Windows
- Detect current architecture as default argument to build script
- Use x64 always on macOS .NET 5 tests, as there is no arm64 release of .NET 5 for macOS
=> Fix tests on macOS/arm64

.build/TestTargetFramework.props, .build/azure-templates/run-tests-on-os.yml, .build/runbuild.ps1, Directory.Build.targets, azure-pipelines.yml, src/J2N/J2N.csproj, src/J2N/Text/CharArrayExtensions.cs, src/J2N/Text/StringBuilderExtensions.cs, src/J2N/Text/StringExtensions.cs, tests/Directory.Build.targets, tests/NUnit/J2N.TestFramework/J2N.TestFramework.csproj, tests/NUnit/J2N.Tests/J2N.Tests.csproj
Closes #119.
- Added target and tests for `net9.0`
- Removed target for `net6.0`
- Changed to use `net6.0` as the target to test `netstandard2.1`
- Fixed sort order for tests so `J2N.Tests.dll` runs first
- Removed support for binary serialization in `net9.0` (it is deprecated in `net8.0` and lower)
- Suppressed CA2265 build warnings, since we intend to compare against a default `ReadOnlySpan<char>` instance rather than empty.
- Changed publish output to publish each project to an individual directory
=> Added net9.0 target + tests

.build/dependencies.props, tests/J2N.TestUtilities/PlatformDetection.cs, tests/Xunit/J2N.Collections.Concurrent.LurchTable.Tests/LurchTable.Tests.Concurrent.cs, tests/Xunit/J2N.Collections.Generic.HashSet.Tests/HashSet.Generic.Tests.cs, tests/Xunit/J2N.Collections.Generic.LinkedHashSet.Tests/LinkedHashSet.Generic.Tests.cs, tests/Xunit/J2N.Collections.Generic.SortedSet.Tests/SortedSet.Generic.Tests.cs, tests/Xunit/J2N.TestCommon/Collections/ICollectionTest.cs, tests/Xunit/J2N.TestUtilities.Xunit/AssertExtensions.cs, tests/Xunit/J2N.TestUtilities.Xunit/J2N.TestUtilities.Xunit.csproj, tests/Xunit/J2N.TestUtilities.Xunit/compatibility/CallerArgumentExpressionAttribute.cs
`xunit` had breaking changes between 2.4.1 and 2.9.3. This bumps to 2.9.3 and fixes the issues that stem from the breaking API changes.
It also bumps `xunit.runner.visualstudio` to the latest supported by the platform. 2.8.2 on `net47`, `net471`, and `net6.0`. 3.1.5 on all of the others.
This also patches many build warnings that resulted from the upgrade and adds a few missing `[ConditionalFact]` attributes to LurchTable.Tests.Concurrent.
`AssertExtensions` was also bumped from some unknown version to v10.0.0-rc.1.25451.107.
=> Upgraded xunit to 2.9.3
